"""File storage protocol for uploads and model artifacts.

Today's implementation is the local disk; an object store (S3, GCS) can implement the
same protocol later. ``local_path`` exists because parsers (PyMuPDF) need a real file:
a remote implementation would download to a temporary file and return that path.
"""

from typing import BinaryIO, ContextManager, Protocol


class FileStorage(Protocol):
    def write(self, key: str, data: bytes) -> None: ...
    def open_writer(self, key: str) -> ContextManager[BinaryIO]: ...
    def read(self, key: str) -> bytes: ...
    def exists(self, key: str) -> bool: ...
    def delete(self, key: str) -> None: ...
    def local_path(self, key: str) -> str: ...
