/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check that actively probes dependencies instead of asserting status.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Csv
         * @description Ingest an arbitrary CSV file dynamically with zero synthetic column pollution,
         *     robust date parsing (slashes, dots, epoch, ISO), and clean numeric formatting.
         */
        post: operations["ingest_csv_api_v1_ingest_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Get dynamic dashboard summary metrics for a specific dataset.
         */
        get: operations["get_summary_api_v1_data_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Uploads
         * @description Get paginated upload history.
         */
        get: operations["get_uploads_api_v1_data_uploads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Undo Upload
         * @description Undo an upload: drop the dataset's table, metadata, cached schema context and trained models.
         */
        delete: operations["undo_upload_api_v1_data_uploads__upload_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/{dataset_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset Profile
         * @description Per-column statistics: numeric (count, nulls, mean, median, std, min/max, IQR, skewness) and categorical (cardinality, top values).
         */
        get: operations["get_dataset_profile_api_v1_data__dataset_id__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/{dataset_id}/correlations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset Correlations
         * @description Correlation matrix over numeric columns with the pairwise sample size of every cell.
         */
        get: operations["get_dataset_correlations_api_v1_data__dataset_id__correlations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/{dataset_id}/scatter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset Scatter
         * @description Random sample of (x, y) points for two numeric columns, plus the Pearson r over all pairs.
         */
        get: operations["get_dataset_scatter_api_v1_data__dataset_id__scatter_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/{entity_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Data
         * @description Get paginated data for an entity type.
         */
        get: operations["get_data_api_v1_data__entity_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/train": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Train Model
         * @description Train a forecasting model for a dataset as a background job.
         *
         *     Returns ``202`` with a ``job_id`` to poll at ``GET /forecast/jobs/{job_id}``. If a job for the
         *     same dataset is already queued or running, that job is returned instead of starting another.
         *     Pass ``?wait=true`` to block until it finishes and get the legacy ``200`` training response.
         */
        post: operations["train_model_api_v1_forecast_train_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Training Job
         * @description Poll a training job (queued, running, succeeded, failed).
         */
        get: operations["get_training_job_api_v1_forecast_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Predict
         * @description Generate sales forecasts using the trained model for a specific dataset.
         */
        get: operations["predict_api_v1_forecast_predict_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description Get the status of the forecasting model, optionally scoped to a dataset.
         */
        get: operations["get_status_api_v1_forecast_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backtest
         * @description Score the forecasting model on a held-out tail window (MAE/MAPE/RMSE).
         */
        get: operations["backtest_api_v1_forecast_backtest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Scenario
         * @description Execute a counterfactual What-If simulation with mutated business levers and aligned lever contributions.
         *
         *     Set ``save=true`` (optionally with ``name``) to keep the scenario for later listing and comparison.
         */
        post: operations["simulate_scenario_api_v1_forecast_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Simulations
         * @description List saved what-if scenarios (newest first), optionally scoped to a dataset.
         */
        get: operations["list_simulations_api_v1_forecast_simulations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/simulations/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare Simulations
         * @description Compare saved scenarios side by side: each metric lists one value per run, aligned to ``run_ids``.
         */
        get: operations["compare_simulations_api_v1_forecast_simulations_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Query
         * @description Execute a natural language query against the warehouse data.
         */
        post: operations["execute_query_api_v1_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description Upload a document, parse it, chunk it, and store in vector db.
         */
        post: operations["upload_document_api_v1_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Documents
         * @description Semantic search against the vector database.
         */
        post: operations["search_documents_api_v1_documents_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/explain/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Explain Forecast
         * @description Get a factor-attribution explanation for a forecast.
         */
        get: operations["explain_forecast_api_v1_forecast_explain__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/explain-prescribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Explain Prescribe
         * @description Get unified forecast explanation with factor attribution, anomaly detection, and prescriptive actions.
         */
        get: operations["explain_prescribe_api_v1_forecast_explain_prescribe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnomalyRootCause
         * @description Likely causes of a flagged anomaly. Every driver and document listed was actually returned by the
         *     attribution / document search; the summary may only cite them.
         */
        AnomalyRootCause: {
            /** Attribution Date */
            attribution_date: string;
            /** Method */
            method?: string | null;
            /** Drivers */
            drivers: components["schemas"]["RootCauseDriver"][];
            /** Documents */
            documents: components["schemas"]["RootCauseDocument"][];
            /** Summary */
            summary: string;
            /**
             * Summary Source
             * @description llm | deterministic
             */
            summary_source: string;
        };
        /**
         * BacktestResponseData
         * @description Held-out evaluation of the forecasting model (MAE/MAPE/RMSE).
         */
        BacktestResponseData: {
            /** Dataset Id */
            dataset_id?: string | null;
            /** Data Points Used */
            data_points_used: number;
            /** Test Days */
            test_days: number;
            /** Train Points */
            train_points: number;
            /** Mae */
            mae: number;
            /** Rmse */
            rmse: number;
            /** Mape */
            mape?: number | null;
            /**
             * Model Tier
             * @description Tier of the model that was backtested.
             */
            model_tier?: string | null;
            /** Test Start */
            test_start: string;
            /** Test End */
            test_end: string;
        };
        /** Body_ingest_csv_api_v1_ingest_csv_post */
        Body_ingest_csv_api_v1_ingest_csv_post: {
            /** File */
            file: string;
        };
        /** Body_upload_document_api_v1_documents_upload_post */
        Body_upload_document_api_v1_documents_upload_post: {
            /** File */
            file: string;
        };
        /** ChartSpec */
        ChartSpec: {
            /**
             * Type
             * @enum {string}
             */
            type: "line" | "bar" | "scatter" | "pie" | "area";
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** X Key */
            x_key: string;
            /** Y Keys */
            y_keys: string[];
            /** Data */
            data: {
                [key: string]: unknown;
            }[];
        };
        /** ChunkResponse */
        ChunkResponse: {
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
            /** Score */
            score: number;
            /** Text */
            text: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** DocumentSearchRequest */
        DocumentSearchRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 4
             */
            top_k: number;
        };
        /** DocumentSearchResponse */
        DocumentSearchResponse: {
            /** Results */
            results: components["schemas"]["ChunkResponse"][];
        };
        /** DocumentUploadResponse */
        DocumentUploadResponse: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Chunk Count */
            chunk_count: number;
            /** Status */
            status: string;
        };
        /** EntityListResponseData */
        EntityListResponseData: {
            /** Records */
            records: {
                [key: string]: unknown;
            }[];
        };
        /**
         * EntityType
         * @description Business entity types that can be uploaded and queried.
         *
         *     Inherits from str so it can be used directly in URL paths
         *     and serialized to JSON without conversion.
         * @enum {string}
         */
        EntityType: "sales" | "products" | "customers" | "inventory" | "suppliers";
        /**
         * ExplainPrescribeResponseData
         * @description Unified response combining forecast, factor attribution, anomaly detection, and prescriptive actions.
         */
        ExplainPrescribeResponseData: {
            /** Forecast Points */
            forecast_points: components["schemas"]["ForecastPointSchema"][];
            shap_drivers: components["schemas"]["ShapDriversPayload"];
            /** Anomaly Detected */
            anomaly_detected: boolean;
            /** Anomaly Description */
            anomaly_description?: string | null;
            anomaly_root_cause?: components["schemas"]["AnomalyRootCause"] | null;
            /** Prescriptive Actions */
            prescriptive_actions: components["schemas"]["src__api__schemas__explain_prescribe__PrescriptiveAction"][];
            /** Executive Summary */
            executive_summary: string;
        };
        /** ForecastPoint */
        ForecastPoint: {
            /** Date */
            date: string;
            /** Predicted */
            predicted: number;
            /** Lower Bound */
            lower_bound: number;
            /** Upper Bound */
            upper_bound: number;
        };
        /**
         * ForecastPointSchema
         * @description A forecast point for the explain-prescribe response.
         */
        ForecastPointSchema: {
            /** Date */
            date: string;
            /** Predicted */
            predicted: number;
            /** Lower Bound */
            lower_bound: number;
            /** Upper Bound */
            upper_bound: number;
        };
        /** ForecastPredictResponseData */
        ForecastPredictResponseData: {
            model_info: components["schemas"]["ModelInfo"];
            /** Dataset Id */
            dataset_id?: string | null;
            /** History */
            history: components["schemas"]["HistoryPoint"][];
            /** Forecast */
            forecast: components["schemas"]["ForecastPoint"][];
        };
        /** ForecastStatusResponseData */
        ForecastStatusResponseData: {
            /** Model Available */
            model_available: boolean;
            /** Dataset Id */
            dataset_id?: string | null;
            /** Trained At */
            trained_at?: string | null;
            /** Data Points Used */
            data_points_used?: number | null;
            /** Granularity */
            granularity?: string | null;
            /** Date Range */
            date_range?: {
                [key: string]: string;
            } | null;
            /**
             * Model Tier
             * @description linear | prophet | prophet_lgbm
             */
            model_tier?: string | null;
        };
        /** ForecastTrainRequest */
        ForecastTrainRequest: {
            /**
             * Granularity
             * @default daily
             * @enum {string}
             */
            granularity: "daily" | "weekly" | "monthly";
            /** Dataset Id */
            dataset_id?: string | null;
        };
        /** ForecastTrainResponseData */
        ForecastTrainResponseData: {
            /** Job Id */
            job_id?: string | null;
            /** Message */
            message: string;
            /** Training Id */
            training_id: string;
            /** Dataset Id */
            dataset_id?: string | null;
            /** Data Points Used */
            data_points_used: number;
            /** Date Range */
            date_range: {
                [key: string]: string;
            };
            /** Estimated Time Seconds */
            estimated_time_seconds: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryPoint */
        HistoryPoint: {
            /** Date */
            date: string;
            /** Actual */
            actual: number;
        };
        /**
         * MetaSchema
         * @description Generic metadata wrapper that can include pagination or other stats.
         */
        MetaSchema: {
            pagination?: components["schemas"]["PaginationMeta"] | null;
            /** Processing Time Ms */
            processing_time_ms?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** ModelInfo */
        ModelInfo: {
            /** Trained At */
            trained_at?: string | null;
            /** Data Points Used */
            data_points_used: number;
            /** Granularity */
            granularity: string;
            /** Dataset Id */
            dataset_id?: string | null;
        };
        /**
         * PaginationMeta
         * @description Pagination metadata.
         */
        PaginationMeta: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Count */
            total_count: number;
            /** Total Pages */
            total_pages: number;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Question */
            question: string;
            /** Dataset Id */
            dataset_id?: string | null;
        };
        /** QueryResponseData */
        QueryResponseData: {
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Insights */
            insights?: string[];
            /** Prescriptive Actions */
            prescriptive_actions?: components["schemas"]["src__api__schemas__query__PrescriptiveAction"][];
            /** Charts */
            charts?: components["schemas"]["ChartSpec"][];
            /**
             * Generated Sql
             * @default
             */
            generated_sql: string | null;
            /** Raw Data */
            raw_data?: unknown;
            /**
             * Confidence
             * @default high
             */
            confidence: string;
        };
        /** RootCauseDocument */
        RootCauseDocument: {
            /** Document Id */
            document_id: string;
            /** Document Title */
            document_title: string;
            /** Text Snippet */
            text_snippet: string;
            /** Relevance Score */
            relevance_score: number;
        };
        /** RootCauseDriver */
        RootCauseDriver: {
            /** Feature */
            feature: string;
            /** Contribution */
            contribution: number;
            /**
             * Description
             * @default
             */
            description: string;
            /** Direction */
            direction: string;
        };
        /**
         * SavedSimulationData
         * @description A saved what-if scenario.
         */
        SavedSimulationData: {
            /** Id */
            id: string;
            /** Dataset Id */
            dataset_id?: string | null;
            /** Name */
            name?: string | null;
            /** Mutations */
            mutations: {
                [key: string]: unknown;
            };
            /** Horizon Days */
            horizon_days: number;
            /** Baseline Summary */
            baseline_summary: {
                [key: string]: unknown;
            };
            /** Simulated Summary */
            simulated_summary: {
                [key: string]: unknown;
            };
            /** Delta Metrics */
            delta_metrics: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at?: string | null;
        };
        /** SavedSimulationListData */
        SavedSimulationListData: {
            /** Records */
            records: components["schemas"]["SavedSimulationData"][];
        };
        /**
         * ShapDriverPayload
         * @description A single factor-attribution driver contribution.
         */
        ShapDriverPayload: {
            /** Feature */
            feature: string;
            /** Contribution */
            contribution: number;
            /** Description */
            description: string;
        };
        /** ShapDriverSchema */
        ShapDriverSchema: {
            /** Feature */
            feature: string;
            /** Contribution */
            contribution: number;
            /** Description */
            description: string;
        };
        /**
         * ShapDriversPayload
         * @description Grouped positive and negative attribution drivers.
         */
        ShapDriversPayload: {
            /** Positive */
            positive: components["schemas"]["ShapDriverPayload"][];
            /** Negative */
            negative: components["schemas"]["ShapDriverPayload"][];
        };
        /** ShapExplanationResponse */
        ShapExplanationResponse: {
            /** Product Id */
            product_id?: string | null;
            /** Forecast Date */
            forecast_date: string;
            /** Predicted Value */
            predicted_value: number;
            /** Base Value */
            base_value?: number | null;
            /**
             * Top Positive Drivers
             * @default []
             */
            top_positive_drivers: components["schemas"]["ShapDriverSchema"][];
            /**
             * Top Negative Drivers
             * @default []
             */
            top_negative_drivers: components["schemas"]["ShapDriverSchema"][];
            /** Forces */
            forces?: {
                [key: string]: unknown;
            }[] | null;
            /** Explanation Text */
            explanation_text?: string | null;
            /**
             * Method
             * @default prophet_component_decomposition
             */
            method: string;
            /** Method Note */
            method_note?: string | null;
            /** Document Context */
            document_context?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** SimulationComparisonData */
        SimulationComparisonData: {
            /** Run Ids */
            run_ids: string[];
            /** Runs */
            runs: {
                [key: string]: unknown;
            }[];
            /** Metrics */
            metrics: components["schemas"]["SimulationComparisonMetric"][];
        };
        /** SimulationComparisonMetric */
        SimulationComparisonMetric: {
            /** Metric */
            metric: string;
            /**
             * Values
             * @description One value per run, in run_ids order.
             */
            values: (number | null)[];
        };
        /**
         * SimulationPointSchema
         * @description A single simulation comparison point.
         */
        SimulationPointSchema: {
            /** Date */
            date: string;
            /** Baseline Predicted */
            baseline_predicted: number;
            /** Mutated Predicted */
            mutated_predicted: number;
            /** Delta */
            delta: number;
            /** Delta Pct */
            delta_pct: number;
        };
        /**
         * SimulationRequest
         * @description Request body for counterfactual What-If simulation.
         */
        SimulationRequest: {
            /** Dataset Id */
            dataset_id?: string | null;
            /**
             * Horizon Days
             * @description Forecast horizon in days
             * @default 30
             */
            horizon_days: number;
            /**
             * Unit Cost
             * @description Per-unit cost used for gross profit when the dataset has no cost column (overrides a cost column if both exist).
             */
            unit_cost?: number | null;
            /**
             * Save
             * @description Persist this scenario so it can be listed and compared later.
             * @default false
             */
            save: boolean;
            /**
             * Name
             * @description Optional label for a saved scenario.
             */
            name?: string | null;
            /**
             * Mutations
             * @description Lever mutations. Use percentage ("+15%"), absolute delta ("+5"), or fractional (0.15).
             * @example {
             *       "marketing_spend": "-10%",
             *       "unit_price": "+15%"
             *     }
             */
            mutations: {
                [key: string]: unknown;
            };
        };
        /**
         * SimulationResponseData
         * @description Response data for a counterfactual simulation.
         */
        SimulationResponseData: {
            /** Dataset Id */
            dataset_id?: string | null;
            /**
             * Run Id
             * @description Id of the saved scenario when the request set save=true.
             */
            run_id?: string | null;
            /** Mutations Applied */
            mutations_applied: {
                [key: string]: string;
            };
            /** Baseline Total */
            baseline_total: number;
            /** Mutated Total */
            mutated_total: number;
            /** Total Delta */
            total_delta: number;
            /** Total Delta Pct */
            total_delta_pct: number;
            /** Points */
            points: components["schemas"]["SimulationPointSchema"][];
            /** Available Levers */
            available_levers: string[];
            /** Shap Forces */
            shap_forces?: {
                [key: string]: unknown;
            }[];
            /** Shap Positive Forces */
            shap_positive_forces?: {
                [key: string]: unknown;
            }[];
            /** Shap Negative Forces */
            shap_negative_forces?: {
                [key: string]: unknown;
            }[];
            /**
             * Uncertainty
             * @description Prediction intervals for baseline and scenario, per day aligned with `points`, and the method used.
             */
            uncertainty?: {
                [key: string]: unknown;
            } | null;
            /**
             * Profit
             * @description Gross profit for baseline vs scenario, or {available: false, reason} when cost data is missing.
             */
            profit?: {
                [key: string]: unknown;
            } | null;
            /**
             * Pricing
             * @description Estimated price elasticity and profit-maximising price (null price + reason when not reliable).
             */
            pricing?: {
                [key: string]: unknown;
            } | null;
        };
        /** SuccessResponse[Any] */
        SuccessResponse_Any_: {
            /**
             * Status
             * @default success
             */
            status: string;
            /** Data */
            data: unknown;
            meta?: components["schemas"]["MetaSchema"] | null;
        };
        /** SuccessResponse[BacktestResponseData] */
        SuccessResponse_BacktestResponseData_: {
            /**
             * Status
             * @default success
             */
            status: string;
            data: components["schemas"]["BacktestResponseData"];
            meta?: components["schemas"]["MetaSchema"] | null;
        };
        /** SuccessResponse[DocumentSearchResponse] */
        SuccessResponse_DocumentSearchResponse_: {
            /**
             * Status
             * @default success
             */
            status: string;
            data: components["schemas"]["DocumentSearchResponse"];
            meta?: components["schemas"]["MetaSchema"] | null;
        };
        /** SuccessResponse[DocumentUploadResponse] */
        SuccessResponse_DocumentUploadResponse_: {
            /**
             * Status
             * @default success
             */
            status: string;
            data: components["schemas"]["DocumentUploadResponse"];
            meta?: components["schemas"]["MetaSchema"] | null;
        };
        /** SuccessResponse[EntityListResponseData] */
        SuccessResponse_EntityListResponseData_: {
            /**
             * Status
             * @default success
             */
            status: string;
            data: components["schemas"]["EntityListResponseData"];
            meta?: components["schemas"]["MetaSchema"] | null;
        };
        /** SuccessResponse[ExplainPrescribeResponseData] */
        SuccessResponse_ExplainPrescribeResponseData_: {
            /**
             * Status
             * @default success
             */
            status: string;
            data: components["schemas"]["ExplainPrescribeResponseData"];
            meta?: components["schemas"]["MetaSchema"] | null;
        };
        /** SuccessResponse[ForecastPredictResponseData] */
        SuccessResponse_ForecastPredictResponseData_: {
            /**
             * Status
             * @default success
             */
            status: string;
            data: components["schemas"]["ForecastPredictResponseData"];
            meta?: components["schemas"]["MetaSchema"] | null;
        };
        /** SuccessResponse[ForecastStatusResponseData] */
        SuccessResponse_ForecastStatusResponseData_: {
            /**
             * Status
             * @default success
             */
            status: string;
            data: components["schemas"]["ForecastStatusResponseData"];
            meta?: components["schemas"]["MetaSchema"] | null;
        };
        /** SuccessResponse[ForecastTrainResponseData] */
        SuccessResponse_ForecastTrainResponseData_: {
            /**
             * Status
             * @default success
             */
            status: string;
            data: components["schemas"]["ForecastTrainResponseData"];
            meta?: components["schemas"]["MetaSchema"] | null;
        };
        /** SuccessResponse[QueryResponseData] */
        SuccessResponse_QueryResponseData_: {
            /**
             * Status
             * @default success
             */
            status: string;
            data: components["schemas"]["QueryResponseData"];
            meta?: components["schemas"]["MetaSchema"] | null;
        };
        /** SuccessResponse[SavedSimulationListData] */
        SuccessResponse_SavedSimulationListData_: {
            /**
             * Status
             * @default success
             */
            status: string;
            data: components["schemas"]["SavedSimulationListData"];
            meta?: components["schemas"]["MetaSchema"] | null;
        };
        /** SuccessResponse[ShapExplanationResponse] */
        SuccessResponse_ShapExplanationResponse_: {
            /**
             * Status
             * @default success
             */
            status: string;
            data: components["schemas"]["ShapExplanationResponse"];
            meta?: components["schemas"]["MetaSchema"] | null;
        };
        /** SuccessResponse[SimulationComparisonData] */
        SuccessResponse_SimulationComparisonData_: {
            /**
             * Status
             * @default success
             */
            status: string;
            data: components["schemas"]["SimulationComparisonData"];
            meta?: components["schemas"]["MetaSchema"] | null;
        };
        /** SuccessResponse[SimulationResponseData] */
        SuccessResponse_SimulationResponseData_: {
            /**
             * Status
             * @default success
             */
            status: string;
            data: components["schemas"]["SimulationResponseData"];
            meta?: components["schemas"]["MetaSchema"] | null;
        };
        /** SuccessResponse[TrainingJobData] */
        SuccessResponse_TrainingJobData_: {
            /**
             * Status
             * @default success
             */
            status: string;
            data: components["schemas"]["TrainingJobData"];
            meta?: components["schemas"]["MetaSchema"] | null;
        };
        /**
         * TrainingJobData
         * @description State of a background training job.
         */
        TrainingJobData: {
            /** Job Id */
            job_id: string;
            /** Dataset Id */
            dataset_id?: string | null;
            /** Granularity */
            granularity: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Error */
            error?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * PrescriptiveAction
         * @description A single prioritized prescriptive action.
         */
        src__api__schemas__explain_prescribe__PrescriptiveAction: {
            /** Priority */
            priority: number;
            /** Action */
            action: string;
            /** Expected Impact */
            expected_impact: string;
            /** Timeframe */
            timeframe: string;
        };
        /** PrescriptiveAction */
        src__api__schemas__query__PrescriptiveAction: {
            /** Priority */
            priority: number;
            /** Action */
            action: string;
            /** Expected Impact */
            expected_impact: string;
            /** Timeframe */
            timeframe: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ingest_csv_api_v1_ingest_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_csv_api_v1_ingest_csv_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_v1_data_summary_get: {
        parameters: {
            query?: {
                dataset_id?: string | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_Any_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_uploads_api_v1_data_uploads_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_EntityListResponseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_upload_api_v1_data_uploads__upload_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_Any_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_profile_api_v1_data__dataset_id__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_Any_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_correlations_api_v1_data__dataset_id__correlations_get: {
        parameters: {
            query?: {
                method?: "pearson" | "spearman";
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_Any_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_scatter_api_v1_data__dataset_id__scatter_get: {
        parameters: {
            query: {
                x: string;
                y: string;
                limit?: number;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_Any_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_data_api_v1_data__entity_type__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                sort_by?: string;
                sort_order?: string;
                date_from?: string | null;
                date_to?: string | null;
                search?: string | null;
            };
            header?: never;
            path: {
                entity_type: components["schemas"]["EntityType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_EntityListResponseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    train_model_api_v1_forecast_train_post: {
        parameters: {
            query?: {
                wait?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForecastTrainRequest"];
            };
        };
        responses: {
            /** @description wait=true: training finished */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_ForecastTrainResponseData_"];
                };
            };
            /** @description Training job accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_TrainingJobData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_training_job_api_v1_forecast_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_TrainingJobData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_api_v1_forecast_predict_get: {
        parameters: {
            query?: {
                horizon_days?: number;
                dataset_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_ForecastPredictResponseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_v1_forecast_status_get: {
        parameters: {
            query?: {
                dataset_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_ForecastStatusResponseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_api_v1_forecast_backtest_get: {
        parameters: {
            query?: {
                test_days?: number;
                dataset_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_BacktestResponseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_scenario_api_v1_forecast_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_SimulationResponseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_simulations_api_v1_forecast_simulations_get: {
        parameters: {
            query?: {
                dataset_id?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_SavedSimulationListData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_simulations_api_v1_forecast_simulations_compare_get: {
        parameters: {
            query: {
                /** @description Comma-separated saved simulation ids (2-10), all from one dataset. */
                ids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_SimulationComparisonData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_query_api_v1_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_QueryResponseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_DocumentUploadResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_documents_api_v1_documents_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_DocumentSearchResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_forecast_api_v1_forecast_explain__product_id__get: {
        parameters: {
            query?: {
                /** @description YYYY-MM-DD */
                forecast_date?: string | null;
            };
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_ShapExplanationResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_prescribe_api_v1_forecast_explain_prescribe_get: {
        parameters: {
            query?: {
                horizon_days?: number;
                dataset_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_ExplainPrescribeResponseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
