"""align_sales_and_telemetry

Revision ID: 59156b6e1509
Revises: 599d9b819ad8
Create Date: 2026-09-09 19:33:03.293460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59156b6e1509'
down_revision: Union[str, Sequence[str], None] = '599d9b819ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_business_telemetry',
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('sales_volume', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('marketing_spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('supplier_lead_time_days', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('competitor_discount_pct', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_index(op.f('ix_daily_business_telemetry_date'), 'daily_business_telemetry', ['date'], unique=False)
    op.add_column('sales', sa.Column('id', sa.Uuid(), nullable=False))
    op.add_column('sales', sa.Column('sale_date', sa.Date(), nullable=False))
    op.add_column('sales', sa.Column('product_id', sa.Uuid(), nullable=True))
    op.add_column('sales', sa.Column('customer_id', sa.Uuid(), nullable=True))
    op.add_column('sales', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('sales', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('sales', sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('sales', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('sales', sa.Column('channel', sa.String(length=50), nullable=True))
    op.add_column('sales', sa.Column('product_name', sa.String(length=255), nullable=True))
    op.add_column('sales', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('sales', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.add_column('sales', sa.Column('upload_id', sa.Uuid(), nullable=False))
    op.add_column('sales', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('sales', 'marketing_spend',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('sales', 'supplier_lead_time_days',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               nullable=True)
    op.alter_column('sales', 'competitor_discount_pct',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               nullable=True)
    op.drop_index(op.f('ix_sales_date'), table_name='sales')
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_product_id'), 'sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_sale_date'), 'sales', ['sale_date'], unique=False)
    op.create_foreign_key(None, 'sales', 'upload_records', ['upload_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sales', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'sales', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.drop_column('sales', 'sales_volume')
    op.drop_column('sales', 'date')
    op.drop_column('sales', 'revenue')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('revenue', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('date', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('sales_volume', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    # upgrade() created these unnamed, so they carry Postgres's default <table>_<column>_fkey names.
    op.drop_constraint('sales_customer_id_fkey', 'sales', type_='foreignkey')
    op.drop_constraint('sales_product_id_fkey', 'sales', type_='foreignkey')
    op.drop_constraint('sales_upload_id_fkey', 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_sale_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_product_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.create_index(op.f('ix_sales_date'), 'sales', ['date'], unique=False)
    op.alter_column('sales', 'competitor_discount_pct',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('sales', 'supplier_lead_time_days',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('sales', 'marketing_spend',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.drop_column('sales', 'created_at')
    op.drop_column('sales', 'upload_id')
    op.drop_column('sales', 'customer_name')
    op.drop_column('sales', 'category')
    op.drop_column('sales', 'product_name')
    op.drop_column('sales', 'channel')
    op.drop_column('sales', 'payment_method')
    op.drop_column('sales', 'discount')
    op.drop_column('sales', 'total_amount')
    op.drop_column('sales', 'quantity')
    op.drop_column('sales', 'customer_id')
    op.drop_column('sales', 'product_id')
    op.drop_column('sales', 'sale_date')
    op.drop_column('sales', 'id')
    op.drop_index(op.f('ix_daily_business_telemetry_date'), table_name='daily_business_telemetry')
    op.drop_table('daily_business_telemetry')
    # ### end Alembic commands ###
