"""initial postgres schema

Revision ID: 599d9b819ad8
Revises: 
Create Date: 2026-07-29 15:20:50.936606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '599d9b819ad8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('generated_table_name', sa.String(length=255), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('column_mapping', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generated_table_name')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('sales_volume', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('marketing_spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('supplier_lead_time_days', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('competitor_discount_pct', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_index(op.f('ix_sales_date'), 'sales', ['date'], unique=False)
    op.create_table('shap_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('model_id', sa.String(length=50), nullable=False),
    sa.Column('forecast_date', sa.String(length=50), nullable=False),
    sa.Column('top_positive_drivers', sa.JSON(), nullable=False),
    sa.Column('top_negative_drivers', sa.JSON(), nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shap_cache_forecast_date'), 'shap_cache', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_shap_cache_model_id'), 'shap_cache', ['model_id'], unique=False)
    op.create_index(op.f('ix_shap_cache_product_id'), 'shap_cache', ['product_id'], unique=False)
    op.create_table('upload_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('column_mapping', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("entity_type IN ('sales', 'products', 'customers', 'inventory', 'suppliers')", name='ck_upload_records_entity_type'),
    sa.CheckConstraint("status IN ('processing', 'completed', 'failed')", name='ck_upload_records_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_records_created_at'), 'upload_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_upload_records_entity_type'), 'upload_records', ['entity_type'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('segment', sa.String(length=50), nullable=True),
    sa.Column('first_purchase_date', sa.Date(), nullable=True),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_city'), 'customers', ['city'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_segment'), 'customers', ['segment'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name='ck_suppliers_rating'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index('uq_products_sku', 'products', ['sku'], unique=True, postgresql_where=sa.text('sku IS NOT NULL'))
    op.create_table('inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('reorder_quantity', sa.Integer(), nullable=True),
    sa.Column('warehouse_location', sa.String(length=100), nullable=True),
    sa.Column('last_restocked', sa.Date(), nullable=True),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity_on_hand >= 0', name='ck_inventory_qty'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index('uq_products_sku', table_name='products', postgresql_where=sa.text('sku IS NOT NULL'))
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_customers_segment'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_city'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_upload_records_entity_type'), table_name='upload_records')
    op.drop_index(op.f('ix_upload_records_created_at'), table_name='upload_records')
    op.drop_table('upload_records')
    op.drop_index(op.f('ix_shap_cache_product_id'), table_name='shap_cache')
    op.drop_index(op.f('ix_shap_cache_model_id'), table_name='shap_cache')
    op.drop_index(op.f('ix_shap_cache_forecast_date'), table_name='shap_cache')
    op.drop_table('shap_cache')
    op.drop_index(op.f('ix_sales_date'), table_name='sales')
    op.drop_table('sales')
    op.drop_table('documents')
    op.drop_table('dataset_metadata')
    # ### end Alembic commands ###
